### ISSUE TITLE
Formulaire de la home page -> enlever les check box

### ISSUE THREAD

**Issue by Eliselalique** [entrepreneur-interet-general/CIS-front#106]
Ces deux check box : "J’ai des projets à valoriser" et "J’aimerais être partenaire du projet" n'ont plus vraiment de sens car on va désormais faire des parcours dédié dans l'onglet "nous rejoindre".
On peut donc les enlever du formulaire de la HP

**Comment by JulienParis** [comment]
je propose de juste les mettre en "display : none" au lieu de les effacer : ça risquerait de faire foirer l'envoi du formulaire côté serveur

**Comment by DavidBruant** [comment]
J'ai l'impression que faire #66 corrigera ceci dans la foulée
