### ISSUE TITLE
filtre "sourceurs" à lister par ordre alphabétique

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#115]
<img width="1390" alt="capture d ecran 2019-01-18 10 56 56" src="https://user-images.githubusercontent.com/36261426/51379515-e0b61700-1b0f-11e9-8685-6f4e5e6dc6bd.png">

**Comment by DavidBruant** [comment]
La liste n'est actuellement pas dans le même ordre sur tous les navigateurs
