### ISSUE TITLE
Lissage de l'UI sur la nouvelle interface

### ISSUE THREAD

**Issue by Eliselalique** [entrepreneur-interet-general/CIS-front#124]
Checker et corriger l'UI sur les écrans : 
- Tailles de typo
- Taille des boutons 
- Espacement 
- Alignements 
- Couleurs des fonds 
- Arrondis sur les carrés 
- Ombrages des éléments

**Comment by DavidBruant** [comment]
J'ai du mal à avoir une idée claire de ce qui est à corriger et de quand ce travaille sera terminé
Est-ce que ça serait possible de faire une issue page par page et une issue avec les éléments communs à toutes les pages ?

**Comment by Eliselalique** [comment]
Ça marche je fais ça cette aprem ;)

Le mer. 21 nov. 2018 à 13:14, David Bruant <notifications@github.com> a
écrit :

**Comment by DavidBruant** [comment]
Découpée en d'autres issues
