### ISSUE TITLE
dans fiches listing : remplacer tags sourceurs par tags homogénéisés

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#139]

**Comment by DavidBruant** [comment]
Je ne comprends pas cette issue

**Comment by DavidBruant** [comment]
On n'affiche ni les tags scrappés ni les domaines mais les sous-domaines (la liste de 70)

**Comment by DavidBruant** [comment]
C'est possible de jouer avec les fichiers `NORMALISATIONS_TAGS_....js` pour unifier les tags affichés dans l'UI. Le changement de process de traduction des tags sera revu quand on aura Solidata

**Comment by DavidBruant** [comment]
L'endroit qui a l'air le plus efficace pour faire ça est 
https://github.com/entrepreneur-interet-general/CIS-front/blob/3aed307c06c2b4ce71ef506a697edcdae29913ff/cis/app/frontend/scripts/cisProjectSearchAPI.js#L88-L101
Via cette fonction, les tags spécifiques disparaitraient du front-end pour ne laisser que les tags homogénéisés
