### ISSUE TITLE
Intégrer la lame vidéo à la home page

### ISSUE THREAD

**Issue by Eliselalique** [entrepreneur-interet-general/CIS-front#143]
- réception de la vidéo : vendredi 23 novembre 2018

**Comment by DavidBruant** [comment]
Concernant cette vidéo, je vois 2 choix possibles : 
- héberger sur une plateforme (genre Youtube) et là, je peux récupérer le code d'embed et me débrouiller
- héberger nous-même la vidéo, auquel cas, j'ai besoin qu'elle soit exportée dans 2 formats : MPEG-4/H.264 et WebM (sinon, certains navigateurs ne pourront pas lire la vidéo. [Source](https://caniuse.com/#search=video%20format))
