### ISSUE TITLE
Lissage UI / éléments commun à toutes les pages 

### ISSUE THREAD

**Issue by Eliselalique** [entrepreneur-interet-general/CIS-front#146]
**Barre de navigation** 

- [x]  Taille de la barre de navigation : **60 px** (pas 70px)
- [x] Pour la langue, au lieu d'écrire English, si possible faire un bouton de switch comme celui-ci : 
<img width="103" alt="capture d ecran 2018-11-13 a 15 34 53" src="https://user-images.githubusercontent.com/36261426/48853548-093fc000-edb0-11e8-91b2-f548d5219ed2.png">

- [x] Mettre un signifiant visuel pour indiquer le menu dans lequel on se trouve / utiliser le même code que pour les sous-menus des pages "projet" + "qui sommes-nous", comme ici : 
<img width="1012" alt="capture d ecran 2018-11-21 a 17 10 04" src="https://user-images.githubusercontent.com/36261426/48853685-54f26980-edb0-11e8-9c1a-98991b3b22ee.png">

**Les polices** 
- [x] J'ai l'impression que ce n'est pas exactement la bonne font utilisée dans la version en ligne : elles ne s'appellent pas exactement pareil et du coup le rendu est moins joli que la font Barlow accessible ici : https://fonts.google.com/specimen/Barlow

. Exemple : 
<img width="720" alt="capture d ecran 2018-11-13 a 16 09 16" src="https://user-images.githubusercontent.com/36261426/48853893-cc27fd80-edb0-11e8-97da-2f70ae6ae9c7.png">
-> Maquette : Barlow, bold

<img width="860" alt="capture d ecran 2018-11-13 a 16 10 01" src="https://user-images.githubusercontent.com/36261426/48853904-d2b67500-edb0-11e8-918e-5ea00b1971a2.png">
-> En ligne : Barlow 600, normal 

- [x]  Pas toujours les bonnes tailles de police, globalement les tailles sont : 
Corps de texte : barlow, regular, 18
Boutons : barlow, regular, 14
Header : barlow, bold, 40
Titres niveau 2 : barlow, bold, 28
Texte champs formulaire : barlow, regular, 14
Texte des menus (nav et sous-menus) : barlow, regular, 16
Texte des tags ) : barlow, regular, 12

- [x]  Pas toujours la bonne couleur de corps de texte (exemple : font des filtres plus foncée que font des menus). La couleur de tous les corps de texte (quand ce n'est pas violet) est toujours **#3D3A39**

- [x]  Style des boutons : garder toujours le même (pas tjrs le cas sur le site): 
Bouton 1 (presque tous) : rectangle 45px de haut / 2px arrondis / texte barlow regular 14
Bouton 2 (celui de la home-page) : rectangle 50px de haut / 2px arrondis / texte barlow regular 18

- [ ]  Style de tous les cadres + boutons = arrondis 2px

**Comment by DavidBruant** [comment]
- [ ] Utiliser une variable SASS pour les violets primary
- [ ] Revoir tous les layouts en se basant sur les columns Bulma
- [ ] Mieux nester les sass existants
- [ ] Nettoyer commons.scss

**Comment by DavidBruant** [comment]
Il me reste quelques questions : 

> J'ai l'impression que ce n'est pas exactement la bonne font utilisée

J'ai tenté quelque chose, mais j'aimerais bien en reparler avec toi, parce qu'il a d'autres options

>  Style de tous les cadres + boutons = arrondis 2px

Je ne suis pas sûr d'avoir compris ce morceau ou plutôt, je crois que j'ai besoin d'instructions plus spécifiques
