### ISSUE TITLE
Lissage UI / Moteur de recherche 

### ISSUE THREAD

**Issue by Eliselalique** [entrepreneur-interet-general/CIS-front#149]
Lié à l'issue #146 

- [x]  Pas la bonne couleur de gris de fond : la bonne couleur est #F6F6F6

- [x] Barre de recherche / filtre : hauteur **65px** (et non 51px cf en ligne)

- [x] pas le bon picto loupe dans la barre de recherche
![icon_search](https://user-images.githubusercontent.com/36261426/48899568-3c399080-ee50-11e8-828c-f66ded9c08df.png)

- [x] pas les bon picto chevron (je sais je suis relou :) ) 
![icon_chevron2](https://user-images.githubusercontent.com/36261426/48899572-4065ae00-ee50-11e8-9d67-513e856fdf05.png)

- [x] Il faudrait ferrer les filtres à droite sur la même ligne que le dernier menu (source)

- [x] Si possible rajouter des traits gris (#CBCBCB) pour mettre les filtres dans des cases et signifier qu'il est clickable
<img width="828" alt="capture d ecran 2018-11-21 a 18 29 41" src="https://user-images.githubusercontent.com/36261426/48858350-7016a680-edbb-11e8-82db-82dba2e653cd.png">

- [ ] Quand un filtre est sélectionné, pouvoir faire comprendre visuellement à quel filtre il appartient en mettant en bold (cf image ci dessus)

- [x] Il faudrait la même taille pour les trois boutons : liste /  carte / data

- [x] Pas les bon picto liste / carte / data
![icon_list](https://user-images.githubusercontent.com/36261426/48899502-0f857900-ee50-11e8-816e-d4e88fca3096.png)
![icon_map](https://user-images.githubusercontent.com/36261426/48899513-190ee100-ee50-11e8-848f-cfa5f229bf17.png)
![icon_dataviz](https://user-images.githubusercontent.com/36261426/48899520-1dd39500-ee50-11e8-9a9d-45a67636c601.png)

- [x] Pas le bon picto pour l'adresse : mettre 
![icon_pin](https://user-images.githubusercontent.com/36261426/48899496-0c8a8880-ee50-11e8-9627-035eec86e761.png)

- [x] Ombrage des fiches : X0 Y3 B6 / #D6D6D6

- [x] Enlever le picto lien vers le site : on ne met pas de liens sur la vue liste mais sur la page détaillée cf ci-dessous 

- [x] Liens pour la page "le projet" (cf maquette ci-dessous)
Encadré à droite : Rajouter logo du sourceur + sur le nom du sourceur = lien vers le site du projet sur la page du sourceur si possible. A defaut = lien du site du sourceur

Encadré à gauche : "voir le site du projet" = lien vers le site du projet (ex : www.famileo.fr). 
Si pas de site du projet -> ne pas afficher la mention "voir le site du projet"

<img width="729" alt="capture d ecran 2018-11-22 a 11 17 10" src="https://user-images.githubusercontent.com/36261426/48899219-4dce6880-ee4f-11e8-8f45-21b054603a1d.png">

**Comment by DavidBruant** [comment]
Discuter de quel lien afficher + comment récupérer cette info

**Comment by DavidBruant** [comment]
> Pas les bon picto liste / carte / data

Oooh yeah\
Micro-relou le fait d'avoir à changer d'icone (blanc ou noir) selon si c'est le bouton "sélectionné" ou non\
C'est trop de risque/travail pour ce sprint de faire le truc qui charge les icones dans le HTML pour pouvoir changer la couleur du SVG moi-même, mais je sens la motivation monter

**Comment by DavidBruant** [comment]
> Encadré à droite : Rajouter logo du sourceur + sur le nom du sourceur = lien vers le site du projet sur la page du sourceur si possible. A defaut = lien du site du sourceur

J'ai l'impression qu'il s'agit de #227 
Je l'embarque dans le sprint

> Encadré à gauche : "voir le site du projet" = lien vers le site du projet (ex : www.famileo.fr).
Si pas de site du projet -> ne pas afficher la mention "voir le site du projet"

Ok

Je me rajoute #226 tant que je suis là-dessus parce que c'est facile

**Comment by DavidBruant** [comment]
> Il faudrait ferrer les filtres à droite sur la même ligne que le dernier menu (source)

Aligner l'intérieur des filtres sur le bord droit du bouton du filtre
