### ISSUE TITLE
Ajouter deux verbatims à la HP

### ISSUE THREAD

**Issue by Eliselalique** [entrepreneur-interet-general/CIS-front#186]
- [x] **Julien Kounowski, chef de projet SIILAB pour la DRJSCS Hauts-de-France** 
Pour apporter les travaux et les réalisations de notre laboratoire d'innovation publique et les partager au national sur le champ de l'innovation sociale

- [x] **Steven Bertal, co-fondateur de Génération2Conseil**
Le Carrefour des innovations sociales offre une lisibilité nouvelle du secteur de l'ESS en France, utile pour l'intérêt général et nos activités de conseil.

-> les photos associées sont sur le dossier github

**Comment by DavidBruant** [comment]
Il y a un fichier pour Julien Kounowski, mais il manque son visage sur l'image : 
https://github.com/entrepreneur-interet-general/CIS-front/blob/master/cis/app/static/photos/Portraits_photos_julien_kounowski%20.png

C'est pour bon pour l'autre image

**Comment by DavidBruant** [comment]
Le code est prêt, mais une image n'est pas bonne
Je réouvre l'issue pour garder ça en tête

**Comment by Eliselalique** [comment]
Le portrait est bien ajouté

**Comment by JulienParis** [comment]
portraits et verbatims inclus dans le code, à ceci près qu'ils devront être ensuite modifiés en fonction de la couleur principale qui est/sera adoptée (et il faudra appliquer un filtre de la couleur principale sur le portrait de Julien K. pour éviter que le fond blanc de sa photo tranche trop avec les autres portraits)
