### ISSUE TITLE
Refonte home page

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#19]
- [x] Ecriture du contenu (@Eliselalique )
 - [x] Mise en page et illustrations (@Eliselalique) 
 - [ ] Intégration des contenus (@DavidBruant )

Lien vers la maquette : https://xd.adobe.com/spec/c6062120-6289-458f-73ec-1f7e54ae1940-b037/

**Comment by Eliselalique** [comment]
- [ ] Ecriture du contenu 
- [ ] Mise en page et illustrations
- [ ] Intégration des contenus

**Comment by DavidBruant** [comment]
Il ne faut PAS mettre en prod avant le 30 octobre
Mettre en prod le 26 octobre. Avant la mise en prod, on peut mettre en prod le nouveau design sur des routes temporaires (genre `/beta` `/beta/le-projet`, etc.) et la mise en prod sera seulement de changer des URLs (passer `/beta` en `/`)

**Comment by DavidBruant** [comment]
Le code de cette page est sur #67

**Comment by DavidBruant** [comment]
Shippé en prod : http://carrefourdesinnovationssociales.fr/bientot/
