### ISSUE TITLE
Refonte page "le projet"

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#20]
Page "le projet" dans la barre de nav 
Sous onglets : A propos / Les outils techniques / Ils parlent de nous / Récompenses

- [x] Ecriture du contenu (@Eliselalique )
- [x] Mise en page et illustrations (@Eliselalique )
- [ ] Intégration des contenus (@DavidBruant )

Lien vers la maquette : https://xd.adobe.com/spec/c6062120-6289-458f-73ec-1f7e54ae1940-b037/

**Comment by DavidBruant** [comment]
Suite à discussion avec @Eliselalique, c'est ok de faire le même carroussel que sur la home pour la page "le projet"

**Comment by DavidBruant** [comment]
Une partie est fait par #100

**Comment by DavidBruant** [comment]
Fini dans #101
