### ISSUE TITLE
Plusieurs pins sont géolocalisées au même endroit et donc les projets "en-dessous" ne sont pas accessibles

### ISSUE THREAD

**Issue by DavidBruant** [entrepreneur-interet-general/CIS-front#210]

**Comment by JulienParis** [comment]
clusteristation  : https://github.com/Leaflet/Leaflet.markercluster
overlapping markers : https://stackoverflow.com/questions/24220106/overlappingmarkerspiderfier-show-which-markers-are-in-a-spiderfy-cluster
