### ISSUE TITLE
Page "nous rejoindre" Contenu + UX

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#22]
- [ ] Contenu du parcours "porteurs de projets" 
- [ ] Contenu du parcours "structure"

**Comment by DavidBruant** [comment]
https://xd.adobe.com/spec/c6062120-6289-458f-73ec-1f7e54ae1940-b037/screen/a18b7949-00a3-4d54-89e6-858394835a86/NOUS-REJOINDRE-1/
