### ISSUE TITLE
Les filtres n'ont pas l'air de fonctionner sous safari

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#222]

**Comment by DavidBruant** [comment]
[Le code écoute l'évènement "input"](https://github.com/entrepreneur-interet-general/CIS-front/blob/99fb2d884c903ed56e8b1f87032d033d0b9056bb/cis/app/frontend/scripts/components/SearchWithFilters.vue#L41) pour être notifié de quand l'utilisateur clic sur un filtre
Toutefois, sur Safari, un `<input type="checkbox">` ne déclenche pas d'évènement "input" dans ce cas-là

La solution va être simple : écouter plutôt l'évènement "change"

**Comment by DavidBruant** [comment]
Dans la page "qui fait quoi", y'a aussi des checkbox, je vais vérifier s'il y a le même problème

**Comment by DavidBruant** [comment]
> Dans la page "qui fait quoi", y'a aussi des checkbox, je vais vérifier s'il y a le même problème

https://github.com/entrepreneur-interet-general/CIS-front/blob/master/cis/app/templates/qui-fait-quoi.html#L197

Nope, évènement "change"
