### ISSUE TITLE
Modifications UX cartographie

### ISSUE THREAD

**Issue by Eliselalique** [entrepreneur-interet-general/CIS-front#237]
Suite aux retours du test utilisateur fait par Mélodie, cartographe au CGET 

- [ ]  Quand on est zoomé sur une partie du territoire et qu’on fait une recherche il va chercher même dans ce qui est extérieur à la vue actuelle. Ce qui fait qu’on a un résultat mais qu’on ne peut pas le voir. La recherche pourrait 1/ avoir pour effet de revenir automatiquement au cadrage national (mais pas pratique si on était intéressé par 1 territoire en particulier) 2/se focaliser sur le territoire du cadrage actuel et sa proximité (mais les retours seront moins nombreux)

- [ ] Les polygones bleus qui indiquent l’emprise des groupements de points au passage de la souris n’ont pas un statut très clair. On pourrait soit les supprimer soit montrer qu’il ne s’agit pas d’un territoire précisément défini en donnant un aspect flouté par exemple, sans contours.

- [ ] Dur d’accéder aux dom… peut être imaginer un filtre supplémentaire géographique qui zoomerait automatiquement sur une région sélectionnée ?

- [ ] Le background de la sidebar (à gauche de la carte, avec les infos) étant de la même couleur que le background global, on a du mal à voir où elle s’arrête en bas. Dès fois le nom des filtres en bas dépasse de la fenêtre.

- [ ] La carte ne prend pas la taille entière de mon écran. Est-ce qu'il serait possible de l'agrandir un peu ? 

<img width="1437" alt="capture d ecran 2019-01-18 10 04 23" src="https://user-images.githubusercontent.com/36261426/51376449-a5641a00-1b08-11e9-82c6-a941372d2195.png">

- [ ] Au clic sur une mini-fiche de la carte, il n'y a pas de lien vers la fiche "déployée", ça devrait être le cas

**Comment by DavidBruant** [comment]
> Quand on est zoomé sur une partie du territoire et qu’on fait une recherche il va chercher même dans ce qui est extérieur à la vue actuelle. 

Proposition actuelle : on auto-zoom quand les résultats de recherche changent et quand on aura le filtre de localisation (#211), on fixera la carte

> Les polygons bleu

à virer

> Dur d’accéder aux dom

#211 

> Le background de la sidebar (à gauche de la carte, avec les infos) étant de la même couleur que le background global, on a du mal à voir où elle s’arrête en bas. Dès fois le nom des filtres en bas dépasse de la fenêtre.

on agrandit la carte et a priori, ça devrait être cool

> La carte ne prend pas la taille entière de mon écran. Est-ce qu'il serait possible de l'agrandir un peu ?

oui, 100vh

> Au clic sur une mini-fiche de la carte, il n'y a pas de lien vers la fiche "déployée", ça devrait être le cas

yes
au retour arrière, il faut revenir sur la carte

**Comment by DavidBruant** [comment]
Vu que je suis dans la customisation des clusters, j'embarque #235 dans la foulée
