### ISSUE TITLE
integration Vue/VueX générale (hors pages login/register) :

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#24]
- [x] pages recherche/carto/dataviz ; 
- [x] une page par projet ; 
- [x] composants...  
- [ ] pages statiques ;

**Comment by DavidBruant** [comment]
Uniquement pour le premier point (page carto + recherche) et le second, j'envisage le plan suivant : 
- [ ] Faire de la carto une vraie SPA
    - [ ] 1 fichier HTML vraiment statique (+ modules, browserify)
    - [ ] Créer tous les composants Vue de cette interface
- [ ] Rajouter du routing côté client
- [ ] Créer une autre route cachée (genre `/search-vue`) pour refaire le moteur de recherche en Vue. Le bouton "carto" devient actif et les onglets permettent de naviguer entre les deux pages
- [ ] Créer les pages projets et route associée
- [ ] Mettre le tout en prod pour tester (le fait que ça soit sur des routes "cachées" permet que le test aie lieu en prod sans dérouter quoi que ce soit)
- [ ] Dès que les tests son concluants, switcher le front-end de l'ancien moteur de recherche pour le nouveau sur la bonne route + supprimer l'ancien front-end du moteur de recherche
- [ ] Remettre en prod

**Comment by DavidBruant** [comment]
#24 n'a implémenté que les parties statiques des composants
Il manque le côté interactif qui nécessitera du *state management* avec Vuex

**Comment by DavidBruant** [comment]
Continuation avec #47. Le reste de la roadmap plus haut arrivera rapidement (première semaine du sprint 2)

**Comment by DavidBruant** [comment]
On est bon là-dessus désormais
