### ISSUE TITLE
Ajouter le logo de la Fondation Crédit Coopératif sur la homepage

### ISSUE THREAD

**Issue by BenedictePachod** [entrepreneur-interet-general/CIS-front#264]
La Fondation Crédit Coopératif est nouveau membre du collectif du CIS et nouveau financeur, besoins : 
- [x] besoin prioritaire : ajouter son logo en homepage dans la catégorie ''ils nous soutiennent''
S'il manque de place pour les logos ''ils nous soutiennent'', possibilité de supprimer le logo Entrepreneur d'intérêt général qui est redondant avec Etalab, moins grand public et moins d'actualité.

- [x] besoin secondaire : ajouter la Fondation comme membre du collectif dans la page ''qui sommes-nous'' (fichier excel à jour)

**Comment by JulienParis** [comment]
logo ajouté à la page d'accueil mais le GSheet "qui fait quoi" n'est pas à jour. C'est ce GSheet qui est utilisé pour mettre à jour le fichier `/static/data/members.csv` de la page `/qui-sommes-nous/qui-fait-quoi`
