### ISSUE TITLE
update version Flask

### ISSUE THREAD

**Issue by DavidBruant** [entrepreneur-interet-general/CIS-front#33]

**Comment by DavidBruant** [comment]
Je créé une issue pour essayer de comprendre cette carte (qui est à "done")
Est-ce que la résolution de ce problème a eu lieu ici : https://github.com/entrepreneur-interet-general/CIS-front/commit/493bc00e73d593a44153d466409e1e17718a62b0#diff-b4ef698db8ca845e5845c4618278f29a ?

@JulienParis Par curiosité (vu que j'y connais rien en flask), pourquoi as-tu fait cette mise à jour ? merci :-)

**Comment by DavidBruant** [comment]
(je ferme direct l'issue vu que c'est fait)

**Comment by JulienParis** [comment]
il y avait un avertissement de sécurité de github sur le requirements.txt, certaines libs étaient repérées comme ayant une faille (notamment l'ancienne version de Flask)
Merci d'avoir créé et fermé l'issue 👍 !
