### ISSUE TITLE
Intégration des demandes des porteurs de projet à être référencés 

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#36]
- court formulaire à remplir en ligne --> contenus + questions à préciser
- envoyé aux membres du collectif au fil de l’eau. 

Bilan au bout de 3 mois. Intérêt pour les contributeurs : élargir la base de recensement

**Comment by BenedictePachod** [comment]
Cette issue est en prod sur le front il me semble et le back office prêt. Est-elle à fermer ?

**Comment by DavidBruant** [comment]
Il s'agit de la page "Nous rejoindre"
Elle est codée et fonctionnelle
Il manque un peu de peaufinage visuel, mais c'est tracé ailleurs (#154)
Je pense qu'on peut fermer en effet
