### ISSUE TITLE
Page "nous rejoindre" Intégration

### ISSUE THREAD

**Issue by Eliselalique** [entrepreneur-interet-general/CIS-front#56]
Dépendante des cartes #22 (Contenu + UX) et #55 (UI)

**Comment by DavidBruant** [comment]
https://xd.adobe.com/spec/c6062120-6289-458f-73ec-1f7e54ae1940-b037/screen/a18b7949-00a3-4d54-89e6-858394835a86/NOUS-REJOINDRE-1/

**Comment by DavidBruant** [comment]
Suite discussion avec Elise, pour l'instant, c'est ok de faire juste le premier écran et mettre l'adresse email sur CIS

**Comment by DavidBruant** [comment]
Suite à discussion avec @Eliselalique et @JulienParis : 
Pour le stockage de données, créer 1 collection pour les structure + 1 collection pour les porteurs de projets. Au sein de chaque collection, mélanger tous les champs à plat (pas nestés) des formulaires du type de personne qui répond
