### ISSUE TITLE
Enlever l'espace vide en haut et en bas de l'illustration HP_lame3_collectif%402x.png de la home 

### ISSUE THREAD

**Issue by DavidBruant** [entrepreneur-interet-general/CIS-front#63]

**Comment by Eliselalique** [comment]
qu'est ce que c'est ?

**Comment by DavidBruant** [comment]
Dans cette image
https://github.com/entrepreneur-interet-general/CIS-front/blob/master/cis/app/static/illustrations/HP_lame3_collectif%402x.png
il y a de l'espace vide/transparent en haut et en bas (et à gauche et à droite) dont je ne connais pas la taille, ça fait que je suis obligé de jouer avec le CSS pour positionner l'image proprement. S'il n'y avait pas ce blanc, ça serait plus simple à positionner

C'est pas un gros truc, certainement pas important pour la sortie du site

**Comment by Eliselalique** [comment]
Ah yes of course ! Dans la nouvelle version cette illustration a changé ce n'est pas la même. Donc je vais supprimer cette issue et en créer une autre pour changer l'illustration de cette lame :)

**Comment by DavidBruant** [comment]
Ah oui, je vois que c'est https://github.com/entrepreneur-interet-general/CIS-front/blob/master/cis/app/static/illustrations/Projet_collectif.png (pour laquelle l'espace vide est suffisamment petit pour ne pas être un problème)
pardon, je vais faire une autre issue plutôt concernant le nettoyage du dossier `illustrations`
