### ISSUE TITLE
filtre 'sourceurs' à générer grâce au point d'API openscraper

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#76]
La liste des contributeurs est à générer dynamiquement  : pour le moment il manque tous les nouveaux scrapers ajoutés récemment. En fait ce filtre est généré en appelant l'API d'openscraper permettant de lister les scrapers, par exemple : 
`http://www.cis-openscraper.com/api/infos?only_spiders_list=False`
ce qui permet de stocker les object id pour générer la requête de recherche ensuite

**Comment by DavidBruant** [comment]
La liste des sourceurs (membres du collectif) m'a été transmise par Google Spreadsheet (que je transforme en CSV)

Je pense qu'il y a un travail à faire pour réconcilier ce Spreadsheet et la liste des spiders, mais je pense que ça devra attendre après le 30 octobre
Il est possible que j'échoue à afficher le nombre de "projets partagés" ([maquette](https://xd.adobe.com/spec/c6062120-6289-458f-73ec-1f7e54ae1940-b037/screen/ceec81e1-1b3e-41ef-9246-b1a2f35bb4ec/LES-MEMBRE-DU-COLLECTIF/)) pour le 30 octobre à cause de ça

**Comment by JulienParis** [comment]
du coup cet issue est un duplicate de #61

**Comment by DavidBruant** [comment]
Pas exactement
#61 concerne l'appel d'API (performance). Cet appel était utilisé pour remplir le nom du sourceur dans une page projet
Cette issue concerne la mise à jour dynamique du filtre "sourceurs" (dont la liste vient encore de `/static/json/CHOICES_FILTERS_PARTNERS.js`)

**Comment by JulienParis** [comment]
tu peux checker : http://carrefour-des-innovations-sociales.fr/search
la liste des contributeurs est à jour.
Ce qu'il se passe est que le JSON en question est loadé à cause de la ligne 167 du `main.html` mais après ça se met à jour, en fait c deprecated à ce niveau.
- dans les [anciens filtres ](https://github.com/entrepreneur-interet-general/CIS-front/blob/master/cis/app/templates/navbars/navbar-filters.html) tu verras que les filtres sont générés avec la liste `f_filters_partners` stockée dans le $store
- dans l'ancien store la liste `f_filters_partners` est mise à jour par cette fonction (cf lignes 390-423 de l'[ancien controler](https://github.com/entrepreneur-interet-general/CIS-front/blob/master/cis/app/static/js/cis-vue-controllers.js) ) : 
```
created		: function() {
			console.log(">>> v_navbar_search_filters / initiating ... "); 
			console.log(">>> v_navbar_search_filters / this.f_categories : ", this.f_categories); 
			this.f_queryOpenScraper_infos() ;	
			this.f_queryOpenScraper_stats() ;	
		},

		methods		: {
			
			f_queryOpenScraper_infos : function() {

				var f_filters_partners = this.f_filters_partners ;

				console.log("- v_navbar_search_filters / this.f_filters_partners : ", this.f_filters_partners ) ;

				ajax_query_to_openscraper( url_arg=api_url_current_infos, data_q_slug="" )
					
					.then( function(res){
					
						console.log("- v_navbar_search_filters / res : ", res ) ;

						// f_filters_partners["choices"] = [] ;
						// f_filters_partners["choices"].push(res["spiders"]["spiders_list"]) ;
						
						res["spiders"]["spiders_list"].forEach( function (spider, index) {
							Vue.set(f_filters_partners, index, spider)
						})
						f_filters_partners.sort(compare) ; 
						// this.f_is_partners = true ;
						console.log("- v_navbar_search_filters / this.f_filters_partners : ", f_filters_partners ) ;

				});

},
```

**Comment by JulienParis** [comment]
j'avoue c pas ce qu'il y a de plus élégant mais ça roule

**Comment by JulienParis** [comment]
du coup la maj de cette fonction tiendrait essentiellement à changer le `ajax_query_to_openscraper( url_arg=api_url_current_infos, data_q_slug="" )` par un `fetch...` à ta sauce vers le point d'API sortant uniquement les spiders (cf plus haut), et balancer les résultats dans la variable adhoc du nouveau store que tu as implémenté

**Comment by JulienParis** [comment]
Attention les spiders récupérés sont à la fois les testés et les pas testés. Faudrait veiller à filtrer que les spiders testés pour peupler le filtre "sourceurs" (en attendant que je rajoute l'argument ad hoc dans l'API d'openscraper)... D'ailleurs c'est bizarre par ce que théoriquement le endpoint `http://www.cis-openscraper.com/api/infos?only_spiders_list=true` ne devrait renvoyer que les spiders testés
