### ISSUE TITLE
lien manquant dans la page 'projet'

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#80]
en dessous du lien 'Project ajouté par xxx' Il manque le lien "Voir le projet sur le site sourceur"

En fait il y a 3 liens possiblement affichables (s'ils sont tous scrapés) qui ne renvoient pas tous vers la même chose : 
- le lien vers le site sourceur / root : 'Project ajouté par xxx"
- le lien vers le site sourceur / infos détaillées du projet : "Voir le projet sur le site sourceur"
- le lien vers le site du projet s'il en a un : "Voir le site du projet"

L'idée était de bien séparer/identifier l'info hébergée sur le site sourceur (afin de mettre en valeur le sourceur dans l'encadré) et le site du projet lui-même --> bref d'inciter l'utilisateur à aller sur le site sourceur

**Comment by DavidBruant** [comment]
J'ai l'impression qu'il y a une décision à prendre sur quel lien est pertinent à mettre
