### ISSUE TITLE
"pas de résultat" non implémenté

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#82]
par exemple : une recherche avec les filtres "domaines/développement durable" + "méthodes/évaluation" devrait renvoyer 0 résultats et une page avec "( désolé, pas de résultats )"

Pour l'instant on dirait que si une recherche renvoie 0 résultat les résultats "freeze" et conservent la recherche précédente au lieu d'afficher des résultats vides

**Comment by JulienParis** [comment]
@julien 
- vérifier que ça vide le store
- reproduire le problème

**Comment by DavidBruant** [comment]
A fermer en faveur de #191
