### ISSUE TITLE
z-index de la carto

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#83]
le canevas de la carto est sur un z-index élévé, du coup les filtres dépliés passent "dessous" le canevas...

**Comment by JulienParis** [comment]
de même lorsqu'on scrolle le canvas passe "au-dessus" de la barre de filtre et barre de nav

**Comment by DavidBruant** [comment]
Visiblement appliquer le CSS suivant résout le problème : 

```css
.map .leaflet-container *{
  z-index: 1;
}
```

Il semblerait que ça soit "grâce" à Bulma qui met ses propres `z-index` sur certains éléments

Cette solution est sûrement suffisante à ce stade
