### ISSUE TITLE
Réconcilier la liste des spiders et le Google Spreadsheet des membres du collectif

### ISSUE THREAD

**Issue by DavidBruant** [entrepreneur-interet-general/CIS-front#86]
La liste des sourceurs (membres du collectif) m'a été transmise par Google Spreadsheet (que je transforme en CSV)

Je pense qu'il y a un travail à faire pour réconcilier ce Spreadsheet et la liste des spiders, mais je pense que ça devra attendre après le 30 octobre
Il est possible que j'échoue à afficher le nombre de "projets partagés" ([maquette](https://xd.adobe.com/spec/c6062120-6289-458f-73ec-1f7e54ae1940-b037/screen/ceec81e1-1b3e-41ef-9246-b1a2f35bb4ec/LES-MEMBRE-DU-COLLECTIF/)) pour le 30 octobre à cause de ça

**Comment by JulienParis** [comment]
attention : il y a une différence entre la liste des spiders (sourceurs scrapés, provenant d'OpenScraper) et la liste des membres du collectifs (google spreadsheet) 

Pour la liste des spiders / sourceurs : cf `http://www.cis-openscraper.com/api/infos?only_spiders_list=False` et issue #76

**Comment by JulienParis** [comment]
pour obtenir le nombre de projets partagés par spider/sourceur scrapé : 
- requête vers OpenScraper : `http://www.cis-openscraper.com/api/stats?only_spiders_stats=true` 
- dans le JSON de réponse : @ `counts_stats/spiders_stats` ... ensuite il faut faire le matching en l'ID du spider et son nom en toutes lettres (en tapant dans `http://www.cis-openscraper.com/api/infos?only_spiders_list=true`)

**Comment by JulienParis** [comment]
en plus une fois qu'on a tout ça on pourra commencer à faire des trucs sympas dans l'onglet "données", du genre : http://www.cis-openscraper.com/dataset/dataviz

**Comment by JulienParis** [comment]
je propose de : 
- ajouter une colonne ObjectID correspondant à l'ID du scraper si existant
- créer une nouvelle feuille excel pour export hors colonne emails
- call API/stats pour recup le nombre de projets partagés par acteur

**Comment by DavidBruant** [comment]
Il restera de l'intégrer dans le front-end après

**Comment by DavidBruant** [comment]
En attente de retours de @BenedictePachod sur le google spreadsheet de référence
