### ISSUE TITLE
corriger chanfrein du bloc "XXX projets trouvés"

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#94]
normalement il devrait y avoir un petit arrondi de qqs px sur les angles de ce bloc, comme sur les cards et les boutons "liste | carte | données"

**Comment by DavidBruant** [comment]
Note pour la postérité : 
J'ai eu un petit bug sur le mot "chanfrein"
... puis je l'ai googlé
... puis je me suis dit "ah ! un *rounded corner* !" suivi de "mais pourquoi utiliser ce mot ?"
... puis je me suis dit "ah oui, il vient du monde de l'architecture !"

:-)
