### ISSUE TITLE
limiter la taille des tags sur les cards dans la vue "liste"

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#96]
quand les tags scrapés sont trop longs ça "sort" des cards... pas méga stylé, faudrait juste inclure le slice ça dans le composant "card"

**Comment by DavidBruant** [comment]
As-tu des exemples spécifiques ?

**Comment by DavidBruant** [comment]
Faire #139 avant et on voit si c'est encore un problème
