### ISSUE TITLE
page "le collectif" / photo d'en-tête

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#98]
- [ ] pe ajouter le nombre d'ateliers organisés sur l'année @Eliselalique 
- [x] la photo "sort" du cadre

**Comment by DavidBruant** [comment]
> la photo "sort" du cadre

C'est le cas sur la maquette

**Comment by JulienParis** [comment]
@Eliselalique pour avis sur le nombre d'ateliers... pe même à la place de "1 collectif ouvert"... 
"1" comme chiffre clé je trouve ça un peu mince

**Comment by DavidBruant** [comment]
> > la photo "sort" du cadre
>
> C'est le cas sur la maquette

<img src="https://i.imgflip.com/2l8p1m.jpg" title="made at imgflip.com"/>

=> #99

**Comment by DavidBruant** [comment]
Est-ce que cette issue est encore pertinente ?
